sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (projectile, enemy) {
    projectile.destroy()
    enemy.destroy(effects.disintegrate, 1)
    music.pewPew.play()
    info.changeScoreBy(100)
})
// game loop and events
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile2 = sprites.createProjectileFromSprite(img`
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbffbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111c33f....
        fff........ccddfbbdbf1111ff.....
        .............cfbbdbfccccc.......
        ..............fffff.............
        `, player_plane, projectile_speed, 0)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (player2, enemy2) {
    game.over(false)
})
let enemy_plane: Sprite = null
let running_animation = false
let projectile2: Sprite = null
let projectile_speed = 0
let player_plane: Sprite = null
// sprites
player_plane = sprites.create(img`
    ..............fffcc.............
    ..............fbbddc............
    ...............fbbddc...........
    ccc............fcbbccf..........
    cbbcc.........ffccccccffffff....
    .cbbdc.....fffcbbbbbbbbbbbbbff..
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
    ..fcbbbcccccccbbbcbcb1ff1111bbbf
    ..fccbcccccccccbbbbbb11111111bf.
    .fcbbfffccccccccbbbb11cc33cccf..
    .fbbf...cbdbcccccbbb111c131cf...
    fbbf.....ccdddddfbbbc111c33f....
    fff........ccddfbbdbf1111ff.....
    .............cfbbdbfccccc.......
    ..............fffff.............
    `, SpriteKind.Player)
controller.moveSprite(player_plane)
player_plane.setStayInScreen(true)
// setup
let backgroud_one = sprites.create(assets.image`myImage`, 0)
backgroud_one.setPosition(80, 60)
backgroud_one.z = -10
// variables
let enemy_speed = -75
projectile_speed = 150
game.onUpdate(function () {
    if (player_plane.vx > 10 || player_plane.vy > 10) {
        running_animation = true
        animation.runImageAnimation(
        player_plane,
        [img`
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `,img`
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            `],
        200,
        false
        )
    } else {
        running_animation = false
    }
})
game.onUpdateInterval(1000, function () {
    enemy_plane = sprites.create(img`
        . . . . . . . . . c c 8 . . . . 
        . . . . . . 8 c c c f 8 c c . . 
        . . . c c 8 8 f c a f f f c c . 
        . . c c c f f f c a a f f c c c 
        8 c c c f f f f c c a a c 8 c c 
        c c c b f f f 8 a c c a a a c c 
        c a a b b 8 a b c c c c c c c c 
        a f c a a b b a c c c c c f f c 
        a 8 f c a a c c a c a c f f f c 
        c a 8 a a c c c c a a f f f 8 a 
        . a c a a c f f a a b 8 f f c a 
        . . c c b a f f f a b b c c 6 c 
        . . . c b b a f f 6 6 a b 6 c . 
        . . . c c b b b 6 6 a c c c c . 
        . . . . c c a b b c c c . . . . 
        . . . . . c c c c c c . . . . . 
        `, SpriteKind.Enemy)
    enemy_plane.setVelocity(enemy_speed, 0)
    enemy_plane.setPosition(160, randint(5, 155))
    enemy_plane.setFlag(SpriteFlag.AutoDestroy, true)
})
game.onUpdateInterval(1000, function () {
    for (let index = 0; index < 3; index++) {
        if (info.score() == 100) {
            enemy_plane = sprites.create(img`
                . . . . . . . . . c c 8 . . . . 
                . . . . . . 8 c c c f 8 c c . . 
                . . . c c 8 8 f c a f f f c c . 
                . . c c c f f f c a a f f c c c 
                8 c c c f f f f c c a a c 8 c c 
                c c c b f f f 8 a c c a a a c c 
                c a a b b 8 a b c c c c c c c c 
                a f c a a b b a c c c c c f f c 
                a 8 f c a a c c a c a c f f f c 
                c a 8 a a c c c c a a f f f 8 a 
                . a c a a c f f a a b 8 f f c a 
                . . c c b a f f f a b b c c 6 c 
                . . . c b b a f f 6 6 a b 6 c . 
                . . . c c b b b 6 6 a c c c c . 
                . . . . c c a b b c c c . . . . 
                . . . . . c c c c c c . . . . . 
                `, SpriteKind.Enemy)
            enemy_plane.setVelocity(enemy_speed, 0)
            enemy_plane.setPosition(160, randint(5, 155))
            enemy_plane.setFlag(SpriteFlag.AutoDestroy, true)
        }
    }
})
